### PR TITLE
better support for JNDI URLs

### PR DESCRIPTION
**Pull request by patcheng**
similar to changes for JNDI support in DataObjects. There might be a better way, but I didn't want to upset to much stuff

### CODE REVIEW

**Comment by tpitale** [comment]
Any chance we could get some specs on this?

**Comment by tillsc** [comment]
Specs for JNDI based connections working on travis? That would definitely be a hard one :)

I also have a Tomcat/Oracle11 Setup (but unfortunately without JNDI jet). If someone is basically willing to merge this in I could test the patch in my environment at least.

**Comment by tpitale** [comment]
Oh wow, yeah, it makes a connection to get meta data in order to determine the driver?

**Comment by tillsc** [comment]
Isn't that cool? :)

**Comment by mbj** [comment]
@tpitale Sorry to be annoying, but this does not have any specs either.

**Comment by tpitale** [comment]
I commented on that as well below.

**Comment by mbj** [comment]
@tpitale I think its possible to write specs for this without actually connecting a real DB, message expectations.

**Comment by tpitale** [comment]
Yeah, I could write tests which stub out the bits of the java responses. @tillsc thoughts?

**Pull request merged**
