### PR TITLE
Fix PropertySet's unique_indexes method.

### PR DESCRIPTION
**Pull request by J-F-Liu**
Related Issue: https://github.com/datamapper/dm-core/issues/281

### CODE REVIEW

**Comment by J-F-Liu** [comment]
rake run result:

Finished in 58.35322 seconds

12822 examples, 0 failures, 3505 pending

**Comment by tpitale** [comment]
@J-F-Liu Do you have a failing test case that this fixes?

**Comment by J-F-Liu** [comment]
@tpitale Sorry, I didn't write a test case for this.

**Comment by tpitale** [comment]
@J-F-Liu Looks like you had something from #281's original report. If you could add something I'll merge this.

**Comment by J-F-Liu** [comment]
I write a test case in rspec, but the InMemoryAdapter doesn't have the ability to check uniqueness, so the expected error is not raised.

**Comment by tpitale** [comment]
I don't think we want to include this change to the API for property unique indexes to support a new case at this time. We're drowning maintenance and adding new cases will only make this worse.

**Pull request closed without merging**
